name: pfp_env
channels:
  - conda-forge
dependencies:
  - python
  - configobj
  - cfchecker
  - python-dateutil
  - lmfit
  - matplotlib
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - pyqt
  - pytz
  - scipy
  - statsmodels
  - timezonefinder
  - windrose
  - xarray
  - xlwt
  - xlrd
  - xlsxwriter
